name: Netflix v2 build

on:
  push:
    branches:
      - main
      - router
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: linters
        run: npm run lint
  deploy:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/2021_2_A06367 && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 30m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/2021_2_A06367 && npm run wp
