name: Netflix v2 build

on:
  push:
    branches:
      - main
      - router
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v2
        with:
          extensions: 'js,jsx,ts,tsx'
          annotations: true
